# netlify.toml
[build]
  command = "npm run build"
  publish = "build"

[[redirects]]
  from = "/hls-http/*"
  to   = "/.netlify/functions/hls-http?u=:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/analytics"
  to   = "/.netlify/functions/analytics"
  status = 200
  force = true

[[redirects]]
  from   = "/hls/nyc.tvstream.mx%3A8081/*"
  to     = "http://nyc.tvstream.mx:8081/:splat"
  status = 200
  force  = true

[[redirects]]
  from = "/analytics-event"
  to   = "/.netlify/functions/analytics-event"
  status = 200
  force = true

[[redirects]]
  from = "/hls/*"
  to = "https://:splat"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = '''
  default-src 'self' https: data: blob:;
  script-src 'self' 'unsafe-inline' 'unsafe-eval' https: data: blob:;
script-src-elem 'self' 'unsafe-inline' 'unsafe-eval' https: data: blob:;
  connect-src 'self' https: wss:;
  img-src 'self' data: blob: https:;
  style-src 'self' 'unsafe-inline' https:;
  font-src 'self' data: https:;
  media-src 'self' blob: data: https:;
  frame-src 'self' https:;
  child-src 'self' https:;
  frame-ancestors *;
'''
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[edge_functions]]
path = "/log-view"
function = "log-view"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-store"

[[headers]]
  for = "/**/*.json"
  [headers.values]
    Cache-Control = "public, max-age=60"
